### ISSUE TITLE
Robbery Victim counter to Robin hood

### ISSUE THREAD

**Issue by effinowen** [elightcap/blackmail#1]
EffinOwen: since SOME people dont like the silver whistle currently, would it be possible to add a 10 minute role removal on the @Robbery Victim role and assign it to people who are the target of robin hood?
[4:20 PM] EffinOwen: LMAO i dont know if its possible but maybe if you use the silver whistle and first place already has a robbery victim role, default to second place and do theirs instead, etc to third place and so on?

**Comment by effinowen** [comment]
Roles that are relevant
@Robinhood Immune - This could be a more permanent role that lasts longer than 120 minutes, possibly given by an item or through the hacking channel
@Robbery Victim - This would ideal be a 10minuteish role given after being hacked

**Comment by elightcap** [comment]
This wont be implemented until #4 is implemented.

**Comment by elightcap** [comment]
starting this

**Comment by elightcap** [comment]
im going to start with just making the person with immunity not get robbed and will eventually work on making it move down the list. please submit a secondary issue for that

**Comment by elightcap** [comment]
Done in PR #5 , will keep open for testing soon
