### ISSUE TITLE
Priority 4 - Limit !nuke, !strike, !robinhood to #degen-alley

### ISSUE THREAD

**Issue by effinowen** [elightcap/blackmail#16]
Just to stop people from secretly nuking a channel, I think this command should be only usable in public as to allow people that 10 second chance to change channel name. Alongside this we could maybe make !robinhood and !strike only usable in the public channels so that people see exactly who is using them against them

**Comment by elightcap** [comment]
is this needed? alerts are sent to degen-alley when the stuff is used.

actually you dont even let us use stuff in those channels

**Comment by effinowen** [comment]
Yeah I mean if the alerts are sent from strike and robinhood and nuke to degen city that’s fine, I think the last I saw that robinhood wasn’t being sent and I can’t remember if all the commands say who used them, I wanna make sure that it’s public who is attacking who

**Comment by elightcap** [comment]
robinhood gets sent if its successful, otherwise i dont think its needed.
