### ISSUE TITLE
Potential nuke automation

### ISSUE THREAD

**Issue by effinowen** [elightcap/blackmail#2]
] EffinOwen: also, potential idea for later or maybe if you want to link the git hub I could ask prismatic to take a look at doing it if you want to not worry about it etc since he codes as well
I was thinking we could automate the nuke pretty easily since the hacking is automated now to view the channel names, so once someone hacks and gets the channel name and they buy the nuke it could assign a @USAUSAUSAUSA role, and give them the !nuke "channelname" command
POTENTIALLY you could make it a 10 second count down before the nuke goes through and then it can put either "target not found" or a tenor nuke gif, that way in those 10 seconds when a nuke is initiated if the person is around and notices they are being nuked they can quickly try to change their channel name as a way to counter it

**Comment by elightcap** [comment]
This should be doable.  i have to look into deleteing channels a bit more

**Comment by effinowen** [comment]
client = discord.Client()
@tasks.loop(seconds=1.0, count=10) # repeat after every 10 seconds
async def nuke_countdown():
    print(nuke_countdown.current_loop)

@nuke_countdown.after_loop
async def after_nuke_countdown():
    # try:                    nukeChannel

NukeCountdown.start()

client.run('<your token>')

###########################
Possibility to enable users to !rename their channel during the nuke count down, the task loop apparently allows the bot to receive other commands during the loop so it shouldn't interfere with users ability to use !rename during the loop and then if the after_loop is where it checks channel name before removing all roles from added users? maybe? idk I just googled this shit im sorry I love you

references
https://stackoverflow.com/questions/61920560/how-to-loop-a-task-in-discord-py
https://discordpy.readthedocs.io/en/stable/ext/tasks/index.html
