### ISSUE TITLE
Possible bug needs testing - !build breaks with spaces

### ISSUE THREAD

**Issue by effinowen** [elightcap/blackmail#21]
If you do !build channel-name-like-this 
it works fine, home builder role removed and !privatize works if they have home owner
If you do !build channel name like this
it breaks, does not remove my home builder role and does not allow !privatize even with home owner role

**Comment by effinowen** [comment]
Maybe the command needs to check for more than one space in the command and if there is deny it and say to do the proper format of name-name-name

**Comment by elightcap** [comment]
i still need to test this
