### ISSUE TITLE
Priority 2 - !channelhack command to interact with custom channels

### ISSUE THREAD

**Issue by effinowen** [elightcap/blackmail#22]
Ability to !channelhack #channel-name-here to get added to view/chat access for a private channel after playing the hacking minigame

bottom part seems done
~~Ability to !kick @user to remove someone from the channels custom role if you find someone that you no longer want to be able to view/chat ie a hacker~~

**Comment by effinowen** [comment]
Ability to use !channelhack can be tied to having @The Chosen One role, so users can !channelhack channel-name while they are in the hacking minigame at the end channel, and once they finish in the hacking channel they lose the chosen one role automatically so it does not need to be managed by the bot, this way users can !hack multiple channels but can no longer delay hacking into a channel which is a positive change

**Comment by effinowen** [comment]
Changed !hack to !channelhack to be more descriptive and specific and to free up !hack to start the hacking minigame

**Comment by elightcap** [comment]
added in 93830dd
