### ISSUE TITLE
Priority 5 - !robinhood not being stopped on multiple attempts, looks like @robbery victim isn't applied to the person who got robbed currently

### ISSUE THREAD

**Issue by effinowen** [elightcap/blackmail#24]
[5:40 PM] Ascian: !use silver
[5:40 PM] 
BOT
 Fuckface: Uh oh. Achilles called on that FUCKING robin hood guy again.
[5:40 PM] Ascian: !robinhood
[5:40 PM] 
BOT
 Casino Cashier: I steal from the rich and give to the needy! My name is Robinhood and i am very greedy! I took 216394 from @PrismaticJapan to distribute amongst my Merry People.
[5:40 PM] Ascian: !use silver
[5:40 PM] 
BOT
 Fuckface: Uh oh. Achilles called on that FUCKING robin hood guy again.
[5:40 PM] Ascian: !robinhood
[5:40 PM] 
BOT
 Casino Cashier: I steal from the rich and give to the needy! My name is Robinhood and i am very greedy! I took 197459 from @PrismaticJapan to distribute amongst my Merry People.

**Comment by effinowen** [comment]
Not sure if it was a one off issue or consistently broken

**Comment by elightcap** [comment]
fixed in #30
