### ISSUE TITLE
Can be ignored, maybe 2 months in the future revisit - Potential Automated Minigame

### ISSUE THREAD

**Issue by effinowen** [elightcap/blackmail#3]
Every 4 hours bot would check both poker bot and unbelievabot for money, would remove money from both bots and combine the total together as a prize pool
if prize pool is greater than 0, run the minigame
Message to degen-alley @everyone Time for a minigame! Everyone !roll 1000 now for a chance to win! Only first !roll counts!
Wait 5 minutes, gather if user !roll 1000 the number displayed once, ignore all additional rolls from same user or any rolls not based on !roll 1000
Message to degen-alley @everyone Game is closed, time to pick the winner! Winner is the closest one to my roll!
Bot does !roll 1000
Bot takes number and does "Biggest number - smallest number" based on Users roll and Bots roll
Lowest number closest to 0 wins
Message to degen-alley @everyone @player is the winner!
Bot gives prizepool to user

**Comment by effinowen** [comment]
Could also make the math equation do a check for who the player is an if its @prismatic do "biggest number - smallest number = x ---> x - x = 0"

**Comment by elightcap** [comment]
> import time
>
> t_end = time.time() + 60 * 5
> while time.time() < t_end:
>     do whatever 

This should handle the timer
