### ISSUE TITLE
!ransomware automation

### ISSUE THREAD

**Issue by effinowen** [elightcap/blackmail#37]
!buy Ransomware item
!use Ransomware -> grants "@Dark web" to enable !ransomware command
!ransomware -> remove all members of the "@DC Bank Member" role
done

**Comment by elightcap** [comment]
i need a role grant from having the ransomware item to gate keep the dark web command

**Comment by effinowen** [comment]
Added dark web role to !item-info ransom as well as added role to self assignable roles for now
