### ISSUE TITLE
Make !nuke, !strike, and !robinhood say the name of the user using the command

### ISSUE THREAD

**Issue by effinowen** [elightcap/blackmail#39]
Nuke currently only pings @everyone when it posts to #degen-alley, so it's still hidden who is using the nuke and I'm not positive but I believe it's the same for !robinhood and !strike

Example of message in italics, would want !robinhood and !strike to say something similar
[11:13 PM] 
BOT
 cashier: @everyone NORAD has detected a nuclear warhead _**launched by @player**_! Take cover!
[11:13 PM] 
BOT
 cashier: 10
[11:13 PM] 
BOT
 cashier: 9
[11:13 PM] 
BOT
 cashier: 8
[11:13 PM] 
BOT
 cashier: 7
[11:13 PM] 
BOT
 cashier: 6
[11:14 PM] 
BOT
 cashier: 5
[11:14 PM] 
BOT
 cashier: 4
[11:14 PM] 
BOT
 cashier: 3
[11:14 PM] 
BOT
 cashier: 2
[11:14 PM] 
BOT
 cashier: 1
[11:14 PM] 
BOT
 cashier: 0
[11:14 PM] 
BOT
 cashier: Tactical nuke deployed! https://giphy.com/gifs/HhTXt43pk1I1W

**Comment by elightcap** [comment]
the person has to use the item in degen city prior to calling the item. im not opposed, but i see this as the lowest pri item ever requested in history

**Comment by effinowen** [comment]
That’s true that users have to use the items in advance of calling the command however I’ve witnessed people use the item and not use the command right away, the longest I saw was Sleepy sitting on the !strike command for well over a day,  if roles that provided commands timed out after 5-15 minutes I would say this isn’t needed, but I figured this would be easier than asking you to make those roles expire if not used

I think people will typically use commands right away but there may be times people hold off on using them, like if I use a hack, get a channel name, and then I see someone buy a name change after I !use tactical nuke, I might hold off on using the !nuke till another hack

this would also be a big QoL improvement for users who are AFK when attacked as going back to find out what happened can be a pain, the chat can move quickly if people are gambling even if they use the item and command relatively close together, it’s a lot easier to spot what happened if the user targeted and the user who initiates it are both tagged in the output command since it highlights it yellow

**Comment by effinowen** [comment]
Going back to the middle comment, it might actually be really smart to !use tactical nuke in advance of attempting to nuke someone as when you !use nuke it puts people on high alert, if you gain the role and then wait a few hours, you would be able to use the hacking mini game, get into the !zion channel, and then !nuke from within the Zion channel or their private channel, all the while being almost undetected aside from if someone notices you cycling through the hacking roles. Maybe these attacking roles should be timed to expire after 5 minutes after all?

**Comment by effinowen** [comment]
bump

**Comment by elightcap** [comment]
Have you tried bumping DEEZ NUTS

**Comment by effinowen** [comment]
I still really think it should be one or the other though, either the name of the person using the command should be part of the bots message in degen-alley or the roles for using the commands should be removed after 5 minutes if not used. This would apply to !nuke, !strike, and !robinhood, otherwise people can claim the role needed to use the command, sit on it for a day or two, and do it from a hidden channel, its potentially too obscure, both routes for fixing it would be viable, not sure which one is easier to implement, ideally the 5 minute removal would make the most sense

**Comment by elightcap** [comment]
fixed in https://github.com/elightcap/blackmail/commit/f70b1177e39effcdfcf5a102c967e1c3fb518be2
